### ISSUE TITLE
pyAlienFx & AienwareKBL

### ISSUE THREAD

**Issue by rsm-gh** [Xqua/pyAlienFX#3]
Salut,
 J'ai essayé de te contacter par email mais ça me renvoie les emails comme si ton adresse email n'existait plus. Est ce qu'il serait possible de se contacter? Je te voulais parler par rapport à pyAlienFx & AienwareKBL, et j'avais aussi une petite question

**Comment by Xqua** [comment]
Salut,

Desoler j'etait pas dispo !

oui que veux tu savoir ?

Xqua

**Comment by rsm-gh** [comment]
Sur la derniere version d'alienware-kbl j'ai réussi à faire marcher correctement l'indicateur, le daemon et l'indicateur, il ne reste qu'un petit detail, c'est le power botton avec les modes "on battery, on boot, etc"

Je voulais te demander si jamais vous aviez reussi à les faire marcher. Et puis aussi je me demande si ces modes ne sont que pour le power button.

Sur la derneire version j'ai fait un code qui semble correcte mais pourtant quand j'utilise les autres modes d'ecriture sur le power button, souvent ça me fais bugger les autres lumieres aussi.

J'aimerai bien le reparer pour enfin avoir un logiciel 100% stable!
